// 自定义侧边栏
import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  web: [{ type: 'autogenerated', dirName: 'web' }],
  tools: [{ type: 'autogenerated', dirName: 'tools' }],
  engineering: [{ type: 'autogenerated', dirName: 'engineering' }],
};

export default sidebars;
