// 自定义侧边栏

const sidebars = {
  base: [{ type: 'autogenerated', dirName: 'base' }],
  note: [{ type: 'autogenerated', dirName: 'note' }],
  other: [{ type: 'autogenerated', dirName: 'other' }],
  package: [{ type: 'autogenerated', dirName: 'package' }]
};

export default sidebars;
