// 自定义侧边栏

// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  note: [{ type: 'autogenerated', dirName: 'note' }],
  'components-doc': [{ type: 'autogenerated', dirName: 'components-doc' }],
  'utils-doc': [{ type: 'autogenerated', dirName: 'utils-doc' }],
  'configs-doc': [{ type: 'autogenerated', dirName: 'configs-doc' }]
};

module.exports = sidebars;
