// 自定义侧边栏

// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  base: [{ type: 'autogenerated', dirName: 'base' }],
  note: [{ type: 'autogenerated', dirName: 'note' }],
  other: [{ type: 'autogenerated', dirName: 'other' }],
  package: [{ type: 'autogenerated', dirName: 'package' }],
};

module.exports = sidebars;
